apiVersion: v1
kind: Service
metadata:
  name: eirini-annotate-extension-service
  namespace: cfmr
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: eirini-annotate-extension
   
  ports:
  - protocol: TCP
    name: https
    port: 4545
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-annotate-extension
  namespace: cfmr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eirini-annotate-extension
      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eirini-annotate-extension
     
    spec:
      serviceAccountName: eirinix
      containers:
      - image: hclcnlabs/eirinix-annotate:1.0.0
        name: eirini-annotate-extension
        imagePullPolicy: Always
        env:
        - name: WEBHOOK_SERVICE_NAME
          value: eirini-annotate-extension-service
        - name: WEBHOOK_NAMESPACE
          value: "$ns_fragment"
        - name: POD_NAMESPACE
          value: "$ns_fragment-eirini"
        - name: PRODUCT_ID
          value: "$PRODUCT_ID"
        - name: PRODUCT_METRIC
          value: "$PRODUCT_METRIC"
        - name: PRODUCT_NAME
          value: "$PRODUCT_NAME"
        - name: PRODUCT_VERSION
          value: "$PRODUCT_VERSION"
        - name: PRODUCT_CHARGED_CONTAINERS
          value: "$PRODUCT_CHARGED_CONTAINERS"

      restartPolicy: Always
